server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB # 요청한 파일 한 개의 최대 크기
      max-request-size: 50MB # 요청한 파일 전체의 최대 크기

  batch:
    job:
      names: ${job.name:NONE}
      enabled: false # batch 자동 실행 막음

# Server Health Check
management:
  endpoints:
    web:
      base-path: /api
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: never

# 클러스터링 환경 변수 설정
cluster:
  initZoom: 24
  maxZoom: 20
  minZoom: 0
  nodeSize: 64
  radius: 100
  extent: 512
  crs: MERCATOR

--- #local, dev
spring:
  config:
    activate:
      on-profile: global-dev
  devtools:
    livereload:
      enabled: true

logging:
  level:
    com: debug
    org.hibernate.type: off # 바인딩 할 값을 찍는 로그

--- #prod
spring:
  config:
    activate:
      on-profile: global-prod

logging:
  level:
    com: info